name: additive_bo
channels:
 - defaults
 - conda-forge
 - pytorch
#  - pytorch3d
dependencies:
 - python=3.7
 - pip
 - numpy
 - pandas
 - scipy
 - pytorch
 - scikit-learn
 - rdkit
 - botorch
#  - pytorch3d
 - pip:
    - -e .
    # - -e src/additive_bo/gprotorch/.
    # - rxnfp # --install-option="--no-deps"
    - rxnfp
    - drfp
    # - selfies
    # - graphein==1.4.0
    # - torch-geometric==1.7.2
    - wandb
    - pytorch-lightning
    - scikit-learn-extra
    - jsonargparse[signatures]
