name: additive_bo
channels:
 - defaults
 - conda-forge
 - pytorch
#  - pytorch3d
dependencies:
 - python=3.8
 - pip
 - numpy
 - pandas
 - scipy
 - pytorch
 - scikit-learn
 - rdkit
#  - botorch
#  - pytorch3d
 - pip:
    - -e .
    # - -e src/additive_bo/gprotorch/.
    # - rxnfp # --install-option="--no-deps"
    - rxnfp
    - drfp
    - selfies
    # - graphein==1.4.0
    # - torch-geometric==1.7.2
    - wandb
    - pytorch-lightning
    - scikit-learn-extra
    - jsonargparse[signatures]
    - git+https://github.com/cornellius-gp/gpytorch.git
   #  - git+https://github.com/pytorch/botorch.git
 - pre_commit
   # additional installs:
   # git+https://github.com/pytorch/botorch.git
   # pip install graphein==1.4.0 --no-deps
   # pip install networkx
   # pip install selfies
