command:
  - ${env}
  - python
  - ${program}
  - ${args}
method: grid
metric:
  goal: minimize
  name: sum_acq_values
parameters:
  data.bond_radius:
    value: 3
  data.feature_dimension:
    value: 512
  data.reaction_plate:
    values:
      - 1
      - 2
      - 3
      - 4
  data.representation:
    value: fragprints
  data_selection.init:
    value: random
  data_selection.method:
    value: kmedoids
  data_selection.metric:
    value: jaccard
  data_selection.n_clusters:
    value: 10
  kernel.class_path:
    value: chaos.gprotorch.kernels.fingerprint_kernels.tanimoto_kernel.TanimotoKernel
  model.acquisition_class:
    value: ucb
  model.beta:
    value: 0.1
  model.finetuning:
    value: true
  model.top_n:
    value:
      - 1
      - 3
      - 5
      - 10
  seed_everything:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
  surrogate_model.class_path:
    value: chaos.surrogate_models.gp.GP
  surrogate_model.init_args.standardize:
    value: true
program: train_cli.py
