command:
  - ${env}
  - python
  - ${program}
  - ${args}
method: grid
parameters:
  data.data_path:
    value: data/additives/additive_rxn_screening_plate_1.csv
  data.featurizer.init_args.bond_radius:
    value: 7
  data.featurizer.init_args.nBits:
    value: 512
  data.featurizer.init_args.representation:
    values:
      - drfp
      - rxnfp
  data.featurizer.init_args.task:
    value: reaction_optimization
  data.input_column:
    value: rxn
  data.target_column:
    value: objective
  data_selection.method:
    value: kmeans
  data_selection.metric:
    value: jaccard
  data_selection.n_clusters:
    value: 10
  data_selection.use_pca:
    value: 10
  model.acquisition_class:
    value: ucb
  n_iters:
    value: 100
  seed_everything:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
  surrogate_model.class_path:
    value: chaos.surrogate_models.gp.SimpleGP
  surrogate_model.init_args.covar_module.class_path:
    value: gpytorch.kernels.ScaleKernel
  surrogate_model.init_args.covar_module.init_args.base_kernel.class_path:
    value: gpytorch.kernels.matern_kernel.MaternKernel
  surrogate_model.init_args.likelihood.class_path:
    value: gpytorch.likelihoods.GaussianLikelihood
  surrogate_model.init_args.normalize:
    value: false
  surrogate_model.init_args.standardize:
    value: true
program: train_cli.py
